---
name: cosmic-guacho
description: Cosmic Guacho image
base-image: ghcr.io/ublue-os/cosmic-atomic-main
image-version: 42

modules:
  - from-file: common/common-modules.yaml
  - from-file: common/networking-modules.yaml
  - from-file: common/virt-modules.yaml
